#!/usr/bin/env python3

import tkinter as tk

background_color = "#202e3c"
foreground_color = "#e1d5c2"

root = tk.Tk()
root.config(bg=background_color)
root.title("Themester")

hello_label = tk.Label(root, text="Hello world!")
other_label = tk.Label(root, text="This is Themester")

hello_label.grid(row=0, column=0)
other_label.grid(row=1, column=0)

root.mainloop()
